# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode11.3

script:
  - xcodebuild test -project Example.xcworkspace -scheme Example -destination "platform=iOS Simulator,name=iPhone 11" CODE_SIGNING_REQUIRED=NO
