# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9

script:
  - xcodebuild test -project Example.xcworkspace -scheme Example -destination "platform=iOS Simulator,name=iPhone X" -sdk iphonesimulator13.0 CODE_SIGNING_REQUIRED=NO
