blank_issues_enabled: false
contact_links:
    - name: ⤴️ Upgrade Issue or Installation issue
      url: https://cocoapods.org/pods/razorpay-pod
      about: Need help upgrading to the latest razorpay-pod version? Follow steps from our razorpay-pod docuemntation.
      
    - name: 🤔 Need some help in Integrations
      url: https://razorpay.com/integrations/
      about: Looking for help with your app? Please refer to the integration documentation.
