name: Test Clone Private Repo
on:
  push:
jobs:
  Run-Unit-Test:
    runs-on: macOS-latest # nosemgrep : non-self-hosted-runner
    steps:
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Xcode Version
        run: /usr/bin/xcodebuild -version

      - name: Check out razorpay-ios repository code
        uses: actions/checkout@v2
        with:
          repository: "razorpay/razorpay-ios"
          token: "${{ secrets.CI_BOT_TOKEN }}"
          ref: codeCoverage

      - name: Set permission
        run: exec chmod +x ./.github/scripts/run-uts.sh
      - name: Running Standard Checkout Unit Tests
        run: exec ./.github/scripts/run-uts.sh
