name: Cocoapod Deployment
on: push

jobs:
  list-artifacts:
    runs-on: macOS-latest # nosemgrep : non-self-hosted-runner
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: List Artifacts
        uses: actions/github-script@v6
        id: list-artifacts
        with:
          script: |
            return github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            })

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        env:
          ARTIFACT_ID: ${{ fromJson(steps.list-artifacts.outputs.result).data.artifacts[0].workflow_run.id }}
        with:
          run_id: ${{ env.ARTIFACT_ID }}
