name: Cocoapod Deployment
on: push

jobs:
  list-artifacts:
    runs-on: macOS-latest # nosemgrep : non-self-hosted-runner
    steps:
      - name: Check out razorpay-ios repository code
        uses: actions/checkout@v2

      - name: Get all Artifacts of Repo
        id: list-artifacts
        uses: actions/github-script@v5
        with:
          script: |
            return github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            })

        - name: Print Artifacts List
          run: echo ${{ fromJson(steps.list-artifacts.outputs.result).artifacts  }}
