name: Cocoapod Deployment
on: push

jobs:
  tag-release:
    runs-on: ubuntu-latest # nosemgrep : non-self-hosted-runner
    steps:
      - name: Check out razorpay-ios repository code
        uses: actions/checkout@v2
        with:
          ref: repoDispatchEventTest

      - name: Set permission
        run: exec chmod +x ./.github/scripts/read-podspec-version.sh

      - name: Read version
        id: read-podspec-version
        run: |
          version=$(exec ./.github/scripts/read-podspec-version.sh)
          echo ::set-output name=pod-version::$version

      - name: List Artifacts
        uses: actions/github-script@v6
        id: list-artifacts
        with:
          script: |
            return github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            })

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        env:
          ARTIFACT_ID: ${{ fromJson(steps.list-artifacts.outputs.result).data.artifacts[0].workflow_run.id }}
        with:
          run_id: ${{ env.ARTIFACT_ID }}
          skip_unpack: true
          workflow: Deploy Standard Checkout
          path: ~/Desktop

      - name: Tag release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          POD_VERSION: ${{ steps.read-podspec-version.outputs.pod-version }}
          ARTIFACT_NAME: ${{ fromJson(steps.list-artifacts.outputs.result).data.artifacts[0].name }}
        with:
          tag_name: "${{ env.POD_VERSION }}122"
          release_name: "v_12${{ env.POD_VERSION }}"
          generateReleaseNotes: true
          draft: false
          prerelease: false

      - run: |
          echo "Upload URL ===> ${{ steps.create-release.outputs.upload_url }}"

  cocoapod-release:
    needs: tag-release
    runs-on: macOS-latest # nosemgrep : non-self-hosted-runner
    steps:
      - name: Check out razorpay-ios repository code
        uses: actions/checkout@v2
        with:
          ref: repoDispatchEventTest

      - name: Publish to cocoapods
        env:
          COCOAPOD_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod lib lint razorpay-pod.podspec
